---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  #log_level: debug
  product_version: 14.12.9
  product_name: chef

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
  - name: centos-7.2
  
suites:
  - name: default
    provisioner:
      policyfile: test/fixtures/policies/default.rb
